'use strict';
let licenses=[];const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const secret=()=>sessionStorage.getItem('wntAdminSecret')||'';
function message(text,type='success'){const el=$('msg');el.textContent=text;el.className=`alert${type==='error'?' error':''}`}
async function api(path,opt={}){const response=await fetch(path,{...opt,headers:{'Content-Type':'application/json','X-Admin-Secret':secret(),...(opt.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Không thể kết nối license server.');return data}
function showApp(){const active=Boolean(secret());$('login').classList.toggle('hidden',active);$('app').classList.toggle('hidden',!active)}
function setMetrics(){const count=s=>licenses.filter(x=>x.status===s).length;$('totalMetric').textContent=licenses.length;$('activeMetric').textContent=count('active');$('unusedMetric').textContent=count('unused');$('blockedMetric').textContent=count('blocked')}
const short=(v,n=18)=>!v?'—':v.length>n?`${v.slice(0,n)}…`:v;const date=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(+d)?'—':d.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'})};
function render(){const q=$('search').value.trim().toLowerCase(),rows=licenses.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q));setMetrics();$('rows').innerHTML=rows.map(x=>`<tr><td>${esc(x.license_key)} <button class="mini" data-copy="${esc(x.license_key)}" title="Copy">⧉</button></td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td><td class="muted" title="${esc(x.machine_id)}">${esc(short(x.machine_id))}</td><td class="muted">${esc(date(x.activated_at))}</td><td class="muted">${esc(date(x.last_seen_at))}</td><td>${esc(x.note||'—')}</td><td><div class="actions"><button class="mini" data-action="${x.status==='blocked'?'unblock-key':'block-key'}" data-key="${esc(x.license_key)}" title="${x.status==='blocked'?'Mở khóa':'Khóa'}">${x.status==='blocked'?'○':'⊘'}</button><button class="mini" data-action="reset-key" data-key="${esc(x.license_key)}" title="Reset máy">↻</button><button class="mini danger" data-action="delete-key" data-key="${esc(x.license_key)}" title="Xóa">⌫</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Chưa có license phù hợp.</td></tr>'}
async function loadKeys(){try{const result=await api('/api/admin/list-keys');licenses=result.licenses||[];render();message(`Đã tải ${licenses.length} license.`)}catch(error){message(error.message,'error')}}
async function loadUpdate(){try{const result=await api('/api/update/latest'),u=result.update||{};$('updateVersion').value=u.latestVersion||'';$('updateUrl').value=u.downloadUrl||'';$('updateSha').value=u.sha256||'';$('updateEnabled').checked=Boolean(u.enabled);$('updateRequired').checked=Boolean(u.required)}catch(error){message(error.message,'error')}}
$('loginBtn').onclick=async()=>{const value=$('secret').value.trim();if(!value){$('loginError').textContent='Vui lòng nhập Admin Secret.';$('loginError').classList.remove('hidden');return}const loginBtn=$('loginBtn');loginBtn.disabled=true;loginBtn.textContent='Đang xác thực...';sessionStorage.setItem('wntAdminSecret',value);try{const result=await api('/api/admin/list-keys');licenses=result.licenses||[];$('loginError').classList.add('hidden');showApp();render();message(`Đã đăng nhập · ${licenses.length} license.`);await loadUpdate()}catch(error){sessionStorage.removeItem('wntAdminSecret');$('loginError').textContent=error.message==='Unauthorized'||error.message==='Không có quyền truy cập.'?'Admin Secret không đúng.':error.message;$('loginError').classList.remove('hidden');showApp()}finally{loginBtn.disabled=false;loginBtn.textContent='Đăng nhập an toàn'}};$('secret').onkeydown=e=>{if(e.key==='Enter')$('loginBtn').click()};
$('logoutBtn').onclick=()=>{sessionStorage.removeItem('wntAdminSecret');location.reload()};$('refreshBtn').onclick=()=>Promise.all([loadKeys(),loadUpdate()]);$('loadUpdateBtn').onclick=loadUpdate;$('search').oninput=render;
$('saveUpdateBtn').onclick=async()=>{try{await api('/api/admin/save-update',{method:'POST',body:JSON.stringify({latestVersion:$('updateVersion').value.trim(),downloadUrl:$('updateUrl').value.trim(),sha256:$('updateSha').value.trim(),enabled:$('updateEnabled').checked,required:$('updateRequired').checked})});message('Đã lưu thông tin update.')}catch(error){message(error.message,'error')}};
$('createBtn').onclick=async()=>{try{const result=await api('/api/admin/create-key',{method:'POST',body:JSON.stringify({note:$('note').value.trim()})});$('note').value='';await navigator.clipboard.writeText(result.key).catch(()=>{});message(`Đã tạo và copy ${result.key}`);await loadKeys()}catch(error){message(error.message,'error')}};
$('rows').onclick=async event=>{const copy=event.target.closest('[data-copy]');if(copy){await navigator.clipboard.writeText(copy.dataset.copy);message('Đã copy license key.');return}const button=event.target.closest('[data-action]');if(!button)return;if(['reset-key','delete-key'].includes(button.dataset.action)&&!confirm(`Xác nhận thao tác với ${button.dataset.key}?`))return;try{await api(`/api/admin/${button.dataset.action}`,{method:'POST',body:JSON.stringify({key:button.dataset.key})});await loadKeys()}catch(error){message(error.message,'error')}};
showApp();if(secret()){loadKeys();loadUpdate()}
