'use strict';
let licenses=[];const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const secret=()=>sessionStorage.getItem('wntAdminSecret')||'';
function message(text,type='success'){const el=$('msg');el.textContent=text;el.className=`alert${type==='error'?' error':''}`}
async function api(path,opt={}){const response=await fetch(path,{...opt,headers:{'Content-Type':'application/json','X-Admin-Secret':secret(),...(opt.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Kh么ng th峄?k岷縯 n峄慽 license server.');return data}
function showApp(){const active=Boolean(secret());$('login').classList.toggle('hidden',active);$('app').classList.toggle('hidden',!active)}
function setMetrics(){const count=s=>licenses.filter(x=>x.status===s).length;$('totalMetric').textContent=licenses.length;$('activeMetric').textContent=count('active');$('unusedMetric').textContent=count('unused');$('blockedMetric').textContent=count('blocked')}
const short=(v,n=18)=>!v?'鈥?:v.length>n?`${v.slice(0,n)}鈥:v;const date=v=>{if(!v)return'鈥?;const d=new Date(v);return Number.isNaN(+d)?'鈥?:d.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'})};
function render(){const q=$('search').value.trim().toLowerCase(),rows=licenses.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q));setMetrics();$('rows').innerHTML=rows.map(x=>`<tr><td>${esc(x.license_key)} <button class="mini" data-copy="${esc(x.license_key)}" title="Copy">猝?/button></td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td><td class="muted" title="${esc(x.machine_id)}">${esc(short(x.machine_id))}</td><td class="muted">${esc(date(x.activated_at))}</td><td class="muted">${esc(date(x.last_seen_at))}</td><td>${esc(x.note||'鈥?)}</td><td><div class="actions"><button class="mini" data-action="${x.status==='blocked'?'unblock-key':'block-key'}" data-key="${esc(x.license_key)}" title="${x.status==='blocked'?'M峄?kh贸a':'Kh贸a'}">${x.status==='blocked'?'鈼?:'鈯?}</button><button class="mini" data-action="reset-key" data-key="${esc(x.license_key)}" title="Reset m谩y">鈫?/button><button class="mini danger" data-action="delete-key" data-key="${esc(x.license_key)}" title="X贸a">鈱?/button></div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Ch瓢a c贸 license ph霉 h峄.</td></tr>'}
async function loadKeys(){try{const result=await api('/api/admin/list-keys');licenses=result.licenses||[];render();message(`膼茫 t岷 ${licenses.length} license.`)}catch(error){message(error.message,'error')}}
async function loadUpdate(){try{const result=await api('/api/update/latest'),u=result.update||{};$('updateVersion').value=u.latestVersion||'';$('updateUrl').value=u.downloadUrl||'';$('updateSha').value=u.sha256||'';$('updateEnabled').checked=Boolean(u.enabled);$('updateRequired').checked=Boolean(u.required)}catch(error){message(error.message,'error')}}
async function loadImage(){try{const result=await api('/api/image'),image=result.image||{};$('imagePullUrl').value=image.pullUrl||'';$('imageUsername').value=image.username||'';$('imageToken').value='';$('imageEnabled').checked=Boolean(image.enabled);$('imageTokenState').textContent=image.hasToken?'膼茫 l瓢u token m茫 h贸a':'Kh么ng d霉ng token';$('imageTokenState').classList.toggle('saved',Boolean(image.hasToken))}catch(error){message(error.message,'error')}}
$('loginBtn').onclick=async()=>{const value=$('secret').value.trim();if(!value){$('loginError').textContent='Vui l貌ng nh岷璸 Admin Secret.';$('loginError').classList.remove('hidden');return}const loginBtn=$('loginBtn');loginBtn.disabled=true;loginBtn.textContent='膼ang x谩c th峄眂...';sessionStorage.setItem('wntAdminSecret',value);try{const result=await api('/api/admin/list-keys');licenses=result.licenses||[];$('loginError').classList.add('hidden');showApp();render();message(`膼茫 膽膬ng nh岷璸 路 ${licenses.length} license.`);await Promise.all([loadImage(),loadUpdate()])}catch(error){sessionStorage.removeItem('wntAdminSecret');$('loginError').textContent=error.message==='Unauthorized'||error.message==='Kh么ng c贸 quy峄乶 truy c岷璸.'?'Admin Secret kh么ng 膽煤ng.':error.message;$('loginError').classList.remove('hidden');showApp()}finally{loginBtn.disabled=false;loginBtn.textContent='膼膬ng nh岷璸 an to脿n'}};$('secret').onkeydown=e=>{if(e.key==='Enter')$('loginBtn').click()};
$('logoutBtn').onclick=()=>{sessionStorage.removeItem('wntAdminSecret');location.reload()};$('refreshBtn').onclick=()=>Promise.all([loadKeys(),loadImage(),loadUpdate()]);$('loadUpdateBtn').onclick=loadUpdate;$('loadImageBtn').onclick=loadImage;$('search').oninput=render;
$('saveImageBtn').onclick=async()=>{try{await api('/api/image',{method:'POST',body:JSON.stringify({pullUrl:$('imagePullUrl').value.trim(),username:$('imageUsername').value.trim(),token:$('imageToken').value,enabled:$('imageEnabled').checked})});message('膼茫 谩p d峄g c岷 h矛nh Docker image.');await loadImage()}catch(error){message(error.message,'error')}};
$('saveUpdateBtn').onclick=async()=>{try{await api('/api/admin/save-update',{method:'POST',body:JSON.stringify({latestVersion:$('updateVersion').value.trim(),downloadUrl:$('updateUrl').value.trim(),sha256:$('updateSha').value.trim(),enabled:$('updateEnabled').checked,required:$('updateRequired').checked})});message('膼茫 l瓢u th么ng tin update.')}catch(error){message(error.message,'error')}};
$('createBtn').onclick=async()=>{try{const result=await api('/api/admin/create-key',{method:'POST',body:JSON.stringify({note:$('note').value.trim()})});$('note').value='';await navigator.clipboard.writeText(result.key).catch(()=>{});message(`膼茫 t岷 v脿 copy ${result.key}`);await loadKeys()}catch(error){message(error.message,'error')}};
$('rows').onclick=async event=>{const copy=event.target.closest('[data-copy]');if(copy){await navigator.clipboard.writeText(copy.dataset.copy);message('膼茫 copy license key.');return}const button=event.target.closest('[data-action]');if(!button)return;if(['reset-key','delete-key'].includes(button.dataset.action)&&!confirm(`X谩c nh岷璶 thao t谩c v峄沬 ${button.dataset.key}?`))return;try{await api(`/api/admin/${button.dataset.action}`,{method:'POST',body:JSON.stringify({key:button.dataset.key})});await loadKeys()}catch(error){message(error.message,'error')}};
showApp();if(secret()){loadKeys();loadImage();loadUpdate()}

