create table if not exists licenses (
  id bigint generated by default as identity primary key,
  license_key text unique not null,
  status text not null default 'unused' check (status in ('unused','active','blocked')),
  machine_id text,
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  note text
);
create index if not exists idx_licenses_status on licenses(status);
create index if not exists idx_licenses_machine_id on licenses(machine_id);
create index if not exists idx_licenses_last_seen on licenses(last_seen_at);
create table if not exists app_updates (
  id integer primary key default 1,
  latest_version text,
  download_url text,
  sha256 text,
  enabled boolean not null default false,
  required boolean not null default false,
  updated_at timestamptz not null default now(),
  constraint app_updates_single_row check (id = 1)
);
